site_name: PeninaOcubo
repo_name: danielgonzagat/peninaocubo
repo_url: https://github.com/danielgonzagat/peninaocubo
theme:
  name: material
nav:
  - Home: index.md
  - Guias:
      - Equação Mestra: guides/master_equation.md
      - Equações Completas: guides/PENIN_OMEGA_COMPLETE_EQUATIONS_GUIDE.md
      - IA³ v1.0: guides/README_IA_CUBED_V1.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
