[tool.black]
line-length = 120
target-version = ["py311"]

[tool.ruff]
line-length = 120
target-version = "py311"

[tool.ruff.lint]
select = ["E","F","W","I","UP","B","PL"]
ignore = ["PLR0912","PLR0913","PLR0915","PLR2004","E402","PLC0415"]  # manter estilo rígido sem travar produtividade

[tool.ruff.lint.per-file-ignores]
"test_*.py" = ["E402","PLC0415","PLR2004","RUF001","RUF002"]
