[tool.ruff]
line-length = 100
target-version = "py313"
src = ["penin", "."]
select = ["E","F","I","B","UP","C90","N","W","PL","RUF"]
ignore = ["E203"]  # compat com Black

[tool.black]
line-length = 100
target-version = ["py313"]

[tool.mypy]
python_version = "3.13"
strict = false
warn_unused_ignores = true
warn_redundant_casts = true
disallow_untyped_defs = true
ignore_missing_imports = true

[tool.pytest.ini_options]
addopts = "-q -ra"
testpaths = ["."]
filterwarnings = ["default"]
