name: lint-yaml
on:
  pull_request:
  push:
    branches: [main]

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install yamllint
        run: python -m pip install --upgrade pip yamllint
      - name: Run yamllint (max line=120)
        run: yamllint -d "{extends: default, rules: {line-length: {max: 120}}}" .

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: actionlint
        uses: rhysd/actionlint@v1
