name: Policy matrix
on: [pull_request, push]
jobs:
  policy-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        policy: [staging, strict]
    env:
      FUSE_POLICY: ${{ matrix.policy }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: python -m venv .venv
      - run: . .venv/bin/activate && pip -q install -U pip pytest pyyaml
      - name: Unit tests (loader)
        run: . .venv/bin/activate && pytest -q tests/fusion/test_policy_loader.py
      - name: Smoke (emergent adapter)
        run: . .venv/bin/activate && pytest -q tests/fusion/test_fusion_emergent.py
